[dash]
coldPath=/opt/splunk/var/lib/splunk/dash/colddb
homePath=/opt/splunk/var/lib/splunk/dash/db
thawedPath=/opt/splunk/var/lib/splunk/dash/thaweddb
repFactor=auto

[security]
coldPath=/opt/splunk/var/lib/splunk/security/colddb
homePath=/opt/splunk/var/lib/splunk/security/db
thawedPath=/opt/splunk/var/lib/splunk/security/thaweddb
repFactor=auto

[network]
coldPath=/opt/splunk/var/lib/splunk/network/colddb
homePath=/opt/splunk/var/lib/splunk/network/db
thawedPath=/opt/splunk/var/lib/splunk/network/thaweddb
repFactor=auto

#task-1
[data]
coldPath=/opt/splunk/var/lib/splunk/data/colddb
homePath=/opt/splunk/var/lib/splunk/data/db
thawedPath=/opt/splunk/var/lib/splunk/data/thaweddb
repFactor=auto

#task-3
[class]
coldPath=/opt/splunk/var/lib/class/data/colddb
homePath=/opt/splunk/var/lib/class/data/db
thawedPath=/opt/splunk/var/lib/class/data/thaweddb
repFactor=auto