[http]
disabled = 0

#task-11
[http://security]
disabled = 0
host = MN
token = 3540e729-a02c-4aa1-82b4-26212b552c19
index = security

#task-12
[http://token]
disabled = 0
host = MN
token = eb2d1815-4a60-4cf0-9ff8-d910763b0101
index = token
